version: '3'

services:
  factsbaapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: factsba-docker
    container_name: factsbaapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - '${PORT}:${PORT}'
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    container_name: mongo-factsba
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-factsba
    volumes:
      - ./mongo:/data/db
